CREATE TABLE ProductStatus (
	ProductStatus_ID INT AUTO_INCREMENT PRIMARY KEY,
	BarCode CHAR(16) NOT NULL,
	Status CHAR(20) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL,
	CheckOut TIMESTAMP NULL
)ENGINE=InnoDB;

INSERT INTO ProductStatus (BarCode, Status, CreatedAt)
VALUES ('CR20180926-12345', 'APROVADO', '2018-09-27 21:10:00');

